// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Comfortaa, Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientThemeProvider from "@/components/ClientThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  weight: "400", // adjust weight as needed
  subsets: ["latin"],
});

const quicksand = Quicksand({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Speakhire",
  description: "Generated by Speakhire Org",
};

async function getData() {
  try {
    const AppHeaderRes = await fetch(
      `${process.env.NEXT_PUBLIC_STRAPI_URL}/api/app-header?populate=*`,
      {
        headers: {
          Authorization: `Bearer ${process.env.NEXT_STRAPI_TOKEN}`,
          "Content-Type": "application/json",
        },
        cache: "no-store", // Disables caching (SSR mode)
      }
    );

    if (!AppHeaderRes.ok) throw new Error("Failed to fetch data");

    const AppHeaderData = await AppHeaderRes.json();
    return { ...AppHeaderData?.data };
  } catch (error) {
    console.error("Data fetching error:", error);
    throw error;
  }
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const AppHeaderData = await getData();
  const data = AppHeaderData;

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${comfortaa.className} ${quicksand.className} antialiased`}
        style={{
          minHeight: "100vh",
          overflowX: "hidden",
          margin: 0,
          padding: 0,
          boxSizing: "border-box", // Ensures better layout consistency
        }}
      >
        <ClientThemeProvider>
          <Navbar data={data}/>
          <main
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              width: "100%", // Ensures content adapts to screen size
              padding: "0", // Adds spacing for better readability on mobile
            }}
          >
            {children}
          </main>
          <Footer />
        </ClientThemeProvider>
      </body>
    </html>
  );
}
